slice_name: Sales Revenue
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 30__table
  viz_type: big_number
  slice_id: 171
  x_axis: Date
  time_grain_sqla: P1M
  aggregation: sum
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: SUM("Sales Quantity" * "Price")
    optionName: metric_jiqi1nlk8c_dt3w0bhkwph
    sqlExpression: SUM("Sales Quantity" * "Price")
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: Date
  show_trend_line: true
  start_y_axis_at_zero: false
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.3
  subheader_font_size: 0.15
  subtitle_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":30,"type":"table"},"force":false,"queries":[{"filters":[{"col":"Date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"Date","label":"Date","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"SUM(\"Sales
  Quantity\" * \"Price\")","optionName":"metric_jiqi1nlk8c_dt3w0bhkwph","sqlExpression":"SUM(\"Sales
  Quantity\" * \"Price\")"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["Date"],"columns":[],"aggregates":{"SUM(\"Sales
  Quantity\" * \"Price\")":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]},{"filters":[{"col":"Date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","sqlExpression":"Date","label":"Date","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"SUM(\"Sales
  Quantity\" * \"Price\")","optionName":"metric_jiqi1nlk8c_dt3w0bhkwph","sqlExpression":"SUM(\"Sales
  Quantity\" * \"Price\")"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"pivot","options":{"index":["Date"],"columns":[],"aggregates":{"SUM(\"Sales
  Quantity\" * \"Price\")":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"aggregate","options":{"groupby":[],"aggregates":{"SUM(\"Sales
  Quantity\" * \"Price\")":{"operator":"sum","column":"SUM(\"Sales Quantity\" * \"Price\")"}}}}]}],"form_data":{"datasource":"30__table","viz_type":"big_number","slice_id":171,"x_axis":"Date","time_grain_sqla":"P1M","aggregation":"sum","metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"SUM(\"Sales
  Quantity\" * \"Price\")","optionName":"metric_jiqi1nlk8c_dt3w0bhkwph","sqlExpression":"SUM(\"Sales
  Quantity\" * \"Price\")"},"adhoc_filters":[{"clause":"WHERE","comparator":"No filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"Date"}],"show_trend_line":true,"start_y_axis_at_zero":false,"color_picker":{"a":1,"b":135,"g":122,"r":0},"header_font_size":0.3,"subheader_font_size":0.15,"subtitle_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","rolling_type":"None","extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: ef05050b-0c64-4835-9e3f-fe7911c6145b
version: 1.0.0
dataset_uuid: d594d440-61f0-4e8d-a2f9-89232600cf85
