slice_name: Warehouse Utilization Rate
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 30__table
  viz_type: table
  query_mode: aggregate
  groupby:
  - Store ID
  time_grain_sqla: P1D
  temporal_columns_lookup:
    Date: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Stock Levels
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 818
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: 8e32828e-2423-44d4-9aa0-f21a27dfee53
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(Stock Levels)
    optionName: metric_lay7pym5nt_kh9ng975z6
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: Warehouse Capacity
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 823
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      uuid: f528fb84-fa0e-4f7c-8852-a1051c41cace
      verbose_name: null
      warning_markdown: null
    aggregate: MAX
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: MAX(Warehouse Capacity)
    optionName: metric_ui4kccb2vl_mpo6n57466a
  - expressionType: SQL
    sqlExpression: SUM("Stock Levels") * 100.0 / MAX("Warehouse Capacity")
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Warehouse Utilization Rate (%)
    optionName: metric_qam2w45x01b_toi583i6gm
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: Date
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_z8577qf4pdj_pqq44l3b6u
  - expressionType: SQL
    sqlExpression: '"Stock Levels" is not null'
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_5m9n0vgmkny_1chqi6w51b5
  timeseries_limit_metric:
    expressionType: SQL
    sqlExpression: SUM("Stock Levels") * 100.0 / MAX("Warehouse Capacity")
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM("Stock Levels") * 100.0 / MAX("Warehouse Capacity")
    optionName: metric_7nkp128giis_zgfnt0jfdj9
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: false
  show_totals: false
  table_timestamp_format: smart_date
  include_search: true
  allow_render_html: true
  show_cell_bars: false
  align_pn: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting:
  - column: Warehouse Utilization Rate (%)
    colorScheme: '#EFA1AA'
    operator: <
    targetValue: 50
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":30,"type":"table"},"force":false,"queries":[{"filters":[{"col":"Date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(\"Stock Levels\"
  is not null)"},"applied_time_extras":{},"columns":["Store ID"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Stock
  Levels","description":null,"expression":null,"filterable":true,"groupby":true,"id":818,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"uuid":"8e32828e-2423-44d4-9aa0-f21a27dfee53","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(Stock
  Levels)","optionName":"metric_lay7pym5nt_kh9ng975z6"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Warehouse
  Capacity","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"uuid":"f528fb84-fa0e-4f7c-8852-a1051c41cace","verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(Warehouse
  Capacity)","optionName":"metric_ui4kccb2vl_mpo6n57466a"},{"expressionType":"SQL","sqlExpression":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Warehouse
  Utilization Rate (%)","optionName":"metric_qam2w45x01b_toi583i6gm"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","optionName":"metric_7nkp128giis_zgfnt0jfdj9"},true]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"series_limit_metric":{"expressionType":"SQL","sqlExpression":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","optionName":"metric_7nkp128giis_zgfnt0jfdj9"},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"30__table","viz_type":"table","query_mode":"aggregate","groupby":["Store
  ID"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"Date":true},"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Stock
  Levels","description":null,"expression":null,"filterable":true,"groupby":true,"id":818,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"uuid":"8e32828e-2423-44d4-9aa0-f21a27dfee53","verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(Stock
  Levels)","optionName":"metric_lay7pym5nt_kh9ng975z6"},{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"Warehouse
  Capacity","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"uuid":"f528fb84-fa0e-4f7c-8852-a1051c41cace","verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(Warehouse
  Capacity)","optionName":"metric_ui4kccb2vl_mpo6n57466a"},{"expressionType":"SQL","sqlExpression":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Warehouse
  Utilization Rate (%)","optionName":"metric_qam2w45x01b_toi583i6gm"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"Date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_z8577qf4pdj_pqq44l3b6u"},{"expressionType":"SQL","sqlExpression":"\"Stock
  Levels\" is not null","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_5m9n0vgmkny_1chqi6w51b5"}],"timeseries_limit_metric":{"expressionType":"SQL","sqlExpression":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(\"Stock
  Levels\") * 100.0 / MAX(\"Warehouse Capacity\")","optionName":"metric_7nkp128giis_zgfnt0jfdj9"},"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":false,"show_totals":false,"table_timestamp_format":"smart_date","include_search":true,"allow_render_html":true,"show_cell_bars":false,"align_pn":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[{"column":"Warehouse
  Utilization Rate (%)","colorScheme":"#EFA1AA","operator":"<","targetValue":50}],"comparison_type":"values","extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 25039702-a015-4a7c-80a4-eed7c7d62624
version: 1.0.0
dataset_uuid: d594d440-61f0-4e8d-a2f9-89232600cf85
